Colinluthier test script change
jekhokie/raspberry-noaa-v2 pull request #225
Opened 2021-03-04 22:13 UTC by colinluthier

This adds the start time to the output dialog and adds .sh to the waterfall output dialog.

2021-03-05 01:59 UTC, jekhokie requested changes

2021-03-05 01:59 UTC, jekhokie commented on scripts/testing/start_scanning.sh
> +$(tput setaf 2)
Is this needed/is it duplicated from line 31?

2021-03-05 07:40 UTC, Cirromulus commented on scripts/testing/start_scanning.sh
> +echo "Start scanning at:"
Could you combine both echo blocks?

2021-03-06 19:52 UTC, colinluthier commented
Currently the output looks like this:

```        Scanning for 5h, expect a timed_scan_06.03.21-11.50.csv.gz.png in /home/pi/raspberry-noaa-v2/scripts/testing afterwards.



        Scanning in range 137M:138M:1k, output file is timed_scan_06.03.21-11.50.csv.gz.

        Please note that this script will take precedence over all scheduled capture jobs!

        To stop scanning, either type `killall rtl_power`
        or use the script `/home/pi/raspberry-noaa-v2/scripts/testing/stop_and_finalize_scanning.sh timed_scan_06.03.21-11.50.csv.gz`.
        You can 'peek' while scanning with `/home/pi/raspberry-noaa-v2/scripts/testing/generate_waterfall timed_scan_06.03.21-11.50.csv.gz`.
        (note that gzip output is buffered in chunks, so it won't be updated immediately)
```
Having the date commmand would give the start time in local time as a convenience so it is easier to know when to chack back for results.

2021-03-11 12:55 UTC, jekhokie commented
Closing as this was addressed as part of #250.

2021-03-11 12:55 UTC, closed without merging